In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
data=pd.read_csv("Fat_Supply_Quantity_Data.csv")
data

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0000,21.6397,6.2224,0.0,8.0353,0.6859,0.0327,0.4246,6.1244,...,17.0831,0.3593,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,0.0000,32.0002,3.4172,0.0,2.6734,1.6448,0.1445,0.6418,8.7428,...,9.2443,0.6503,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.0000,14.4175,0.8972,0.0,4.2035,1.2171,0.2008,0.5772,3.8961,...,27.3606,0.5145,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,0.0000,15.3041,1.3130,0.0,6.5545,0.1539,1.4155,0.3488,11.0268,...,22.4638,0.1231,6.8,25,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,0.0000,27.7033,4.6686,0.0,3.2153,0.3872,1.5263,1.2177,14.3202,...,14.4436,0.2469,19.1,NaN,0.293878,0.007143,0.190816,0.095918,98000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),0.0000,16.3261,2.2673,0.0,2.5449,0.6555,0.5707,0.9640,7.0949,...,29.5211,0.1851,25.2,21.2,0.452585,0.004287,0.424399,0.023899,28645000.0,%
166,Vietnam,0.0000,33.2484,3.8238,0.0,3.7155,0.7839,1.1217,0.4079,26.4292,...,5.6211,0.6373,2.1,9.3,0.002063,0.000036,0.001526,0.000501,96209000.0,%
167,Yemen,0.0000,12.5401,2.0131,0.0,11.5271,0.5514,0.3847,0.2564,8.0010,...,23.6312,0.1667,14.1,38.9,0.007131,0.002062,0.004788,0.000282,29826000.0,%
168,Zambia,0.0783,9.6005,1.6113,0.0,14.3225,0.6266,1.0070,0.1343,4.9010,...,15.2848,0.1567,6.5,46.7,0.334133,0.004564,0.290524,0.039045,18384000.0,%
169,Zimbabwe,0.0000,10.3796,2.9543,0.0,9.7922,0.3682,0.2455,0.0614,4.5674,...,26.9396,0.0789,12.3,51.3,0.232033,0.008854,0.190964,0.032214,14863000.0,%

In [3]:
data.isnull().sum()

Country                         0
Alcoholic Beverages             0
Animal Products                 0
Animal fats                     0
Aquatic Products, Other         0
Cereals - Excluding Beer        0
Eggs                            0
Fish, Seafood                   0
Fruits - Excluding Wine         0
Meat                            0
Miscellaneous                   0
Milk - Excluding Butter         0
Offals                          0
Oilcrops                        0
Pulses                          0
Spices                          0
Starchy Roots                   0
Stimulants                      0
Sugar Crops                     0
Sugar & Sweeteners              0
Treenuts                        0
Vegetal Products                0
Vegetable Oils                  0
Vegetables                      0
Obesity                         3
Undernourished                  7
Confirmed                       6
Deaths                          6
Recovered                       6
Active                          8
Population                      0
Unit (all except Population)    0
dtype: int64

In [4]:
data.fillna(method="ffill",inplace=True)

In [5]:
data.Undernourished=data.Undernourished.str.replace("<","")
data.Undernourished=data.Undernourished.astype('float')

In [6]:
data

,Country,Alcoholic Beverages,Animal Products,Animal fats,"Aquatic Products, Other",Cereals - Excluding Beer,Eggs,"Fish, Seafood",Fruits - Excluding Wine,Meat,...,Vegetable Oils,Vegetables,Obesity,Undernourished,Confirmed,Deaths,Recovered,Active,Population,Unit (all except Population)
0,Afghanistan,0.0000,21.6397,6.2224,0.0,8.0353,0.6859,0.0327,0.4246,6.1244,...,17.0831,0.3593,4.5,29.8,0.142134,0.006186,0.123374,0.012574,38928000.0,%
1,Albania,0.0000,32.0002,3.4172,0.0,2.6734,1.6448,0.1445,0.6418,8.7428,...,9.2443,0.6503,22.3,6.2,2.967301,0.050951,1.792636,1.123714,2838000.0,%
2,Algeria,0.0000,14.4175,0.8972,0.0,4.2035,1.2171,0.2008,0.5772,3.8961,...,27.3606,0.5145,26.6,3.9,0.244897,0.006558,0.167572,0.070767,44357000.0,%
3,Angola,0.0000,15.3041,1.3130,0.0,6.5545,0.1539,1.4155,0.3488,11.0268,...,22.4638,0.1231,6.8,25.0,0.061687,0.001461,0.056808,0.003419,32522000.0,%
4,Antigua and Barbuda,0.0000,27.7033,4.6686,0.0,3.2153,0.3872,1.5263,1.2177,14.3202,...,14.4436,0.2469,19.1,25.0,0.293878,0.007143,0.190816,0.095918,98000.0,%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,Venezuela (Bolivarian Republic of),0.0000,16.3261,2.2673,0.0,2.5449,0.6555,0.5707,0.9640,7.0949,...,29.5211,0.1851,25.2,21.2,0.452585,0.004287,0.424399,0.023899,28645000.0,%
166,Vietnam,0.0000,33.2484,3.8238,0.0,3.7155,0.7839,1.1217,0.4079,26.4292,...,5.6211,0.6373,2.1,9.3,0.002063,0.000036,0.001526,0.000501,96209000.0,%
167,Yemen,0.0000,12.5401,2.0131,0.0,11.5271,0.5514,0.3847,0.2564,8.0010,...,23.6312,0.1667,14.1,38.9,0.007131,0.002062,0.004788,0.000282,29826000.0,%
168,Zambia,0.0783,9.6005,1.6113,0.0,14.3225,0.6266,1.0070,0.1343,4.9010,...,15.2848,0.1567,6.5,46.7,0.334133,0.004564,0.290524,0.039045,18384000.0,%
169,Zimbabwe,0.0000,10.3796,2.9543,0.0,9.7922,0.3682,0.2455,0.0614,4.5674,...,26.9396,0.0789,12.3,51.3,0.232033,0.008854,0.190964,0.032214,14863000.0,%

In [7]:
x=data[["Obesity","Undernourished"]]
y=data.Recovered

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.1)
x_test

     Obesity  Undernourished
8       21.9             2.5
73      26.7             2.5
66      28.6             2.5
5       28.5             4.6
166      2.1             9.3
167     14.1            38.9
143      7.4            20.1
69       6.9             8.3
11       3.4            14.7
61       6.6            16.5
112      4.7            16.5
117      7.8            20.3
107      3.8             8.7
21      27.4             3.6
38      28.5             2.5
124     20.1             2.5
35      27.1             2.5

In [ ]:
sns.pairplot(data)

In [ ]:
sns.pairplot(data,x_vars=["Obesity","Undernourished"],y_vars=["Recovered"],diag_kind=None)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
model=LinearRegression()

In [12]:
model.fit(x_train,y_train)

LinearRegression()

In [13]:
y_predict=model.predict(x_test)
y_predict

array([1.70933549, 1.91194528, 1.99214499, 1.9228136 , 0.6627366 ,
       0.25151522, 0.55159836, 0.89635132, 0.55018348, 0.6294478 ,
       0.5492481 , 0.56228153, 0.75309719, 1.90738712, 1.98792395,
       1.63335682, 1.92882943])

In [14]:
model.intercept_

0.8624406471402937

In [15]:
model.coef_

array([ 0.04221037, -0.03100493])

In [16]:
#statsmodels
import statsmodels.formula.api as sm

In [17]:
lr=sm.ols(formula='Recovered ~ Obesity + Undernourished',data=data).fit()

In [18]:
y_sm_predict=lr.predict({"Obesity":28.4,"Undernourished":2.5 })
y_sm_predict

0    2.254443
dtype: float64

In [19]:
lr.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              Recovered   R-squared:                       0.188
Model:                            OLS   Adj. R-squared:                  0.178
Method:                 Least Squares   F-statistic:                     19.33
Date:                Mon, 13 Sep 2021   Prob (F-statistic):           2.82e-08
Time:                        20:49:20   Log-Likelihood:                -332.93
No. Observations:                 170   AIC:                             671.9
Df Residuals:                     167   BIC:                             681.3
Df Model:                           2
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.8164      0.434      1.880      0.062      -0.041       1.674
Obesity            0.0537      0.017      3.233      0.001       0.021       0.087
Undernourished    -0.0353      0.013     -2.682      0.008      -0.061      -0.009
==============================================================================
Omnibus:                       56.958   Durbin-Watson:                   1.848
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              130.055
Skew:                           1.482   Prob(JB):                     5.74e-29
Kurtosis:                       6.094   Cond. No.                         75.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""